server:
  port: 8080

spring:
  application:
    name: FastFlow-API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://11.121.246.88:3306/fastflow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

auth:
  jwt:
    secret: 9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f
    expiration: 3600 # 1小时 (1 * 60 * 60)
  password:
    secret-key: d7b8a2c9e4f10536 # 密码加密 AES 密钥


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: status
      logic-delete-value: 3
      logic-not-delete-value: 1


